volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on: 
      - db
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    depends_on:
      - backend
      - frontend
    build: ./infra/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
